jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: >
      pipelineJob('ds-recruitment-task') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/svshy/ds-recruitment-task.git')
                }
              }
            }
            scriptPath('jenkins/Jenkinsfile')
          }
        }
      }
